---
name: Install zola
description: This action installs zola (https://github.com/getzola/zola)

inputs:
  version:
    description: The version of zola to install, e.g. v0.20.0
    required: false
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          version="$(curl --silent https://api.github.com/repos/getzola/zola/releases/latest | jq -r '.tag_name')"
        else
          version="${{ inputs.version }}"
        fi

        curl --fail-with-body --location --silent "https://github.com/getzola/zola/releases/download/${version}/zola-${version}-$(uname --machine)-unknown-linux-gnu.tar.gz" \
          --output "/tmp/zola.tar.gz"

        tar --extract --file "/tmp/zola.tar.gz" --directory "/usr/local/bin"

        zola --version
