---
name: Install zola
description: This action installs zola (https://github.com/getzola/zola)

inputs:
  version:
    description: The version of zola to install, e.g. v0.20.0
    required: false
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      env:
        ZOLA_VERSION: ${{ inputs.version }}
      run: bash "${{ github.action_path }}/install-zola.sh"
