---
name: 🚀 Deploy Preview

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  deploy-preview:
    name: 🚀 Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@05f17c4a695b4d94b57b59997562c6a4624c64e4 # v3.12.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --branch ${{ github.head_ref }} --commit-hash ${{ github.sha }}
