---
name: 🚀 Deploy Preview

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  deploy-preview:
    name: 🚀 Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: preview
      url: https://preview.jacobwoffenden-com.pages.dev
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: DEBUG
        id: debug
        run: |
          echo "Environment: ${{ environment.name }}"
